# Generated by Django 5.1.6 on 2025-02-21 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('empname', models.TextField()),
                ('empemail', models.EmailField(max_length=254)),
                ('pno', models.IntegerField()),
                ('department', models.TextField(max_length=200)),
                ('designation', models.TextField(max_length=200)),
                ('salary', models.IntegerField()),
                ('date', models.DateField()),
                ('empType', models.TextField()),
                ('address', models.TextField()),
                ('status', models.BooleanField()),
            ],
        ),
    ]
